services:
  api:
    build:
      context: src/
      dockerfile: Dockerfile-api
    volumes:
      - ./src/puzzles.txt:/opt/erastus/puzzles.txt:rw

  ui:
    build:
      context: src
      dockerfile: Dockerfile-ui
    ports:
      - "9000:80"
