FROM alpine
RUN apk add --no-cache g++ make python3 py3-pip && \
    pip install flask gunicorn
WORKDIR /opt/erastus
COPY [".", "."]
RUN make -B

RUN echo API_URL = \'\' > ui/js/config.js

ENTRYPOINT ["make", "api"]
